[2025-02-27T13:16:20.217+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-27T13:16:18.504362+00:00 [queued]>
[2025-02-27T13:16:20.232+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-27T13:16:18.504362+00:00 [queued]>
[2025-02-27T13:16:20.233+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-27T13:16:20.251+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): create_station_informations_table> on 2025-02-27 13:16:18.504362+00:00
[2025-02-27T13:16:20.255+0000] {standard_task_runner.py:57} INFO - Started process 210 to run task
[2025-02-27T13:16:20.260+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'create_station_informations_table', 'manual__2025-02-27T13:16:18.504362+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpfr2in2nv']
[2025-02-27T13:16:20.262+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask create_station_informations_table
[2025-02-27T13:16:20.304+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-27T13:16:18.504362+00:00 [running]> on host 3f89a3e69849
[2025-02-27T13:16:20.391+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='create_station_informations_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T13:16:18.504362+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T13:16:18.504362+00:00'
[2025-02-27T13:16:20.392+0000] {sql.py:262} INFO - Executing: 
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = 'velib_station_details'
            ) THEN
                CREATE TABLE velib_station_details (
                    station_id BIGINT PRIMARY KEY, 
                    capacity INT,                   
                    lat DOUBLE PRECISION,          
                    lon DOUBLE PRECISION,           
                    name VARCHAR(255)
                );
            END IF;
        END
        $$;
    
[2025-02-27T13:16:20.398+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-27T13:16:20.521+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-27T13:16:20.525+0000] {sql.py:375} INFO - Running statement: 
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'public' AND table_name = 'velib_station_details'
            ) THEN
                CREATE TABLE velib_station_details (
                    station_id BIGINT PRIMARY KEY, 
                    capacity INT,                   
                    lat DOUBLE PRECISION,          
                    lon DOUBLE PRECISION,           
                    name VARCHAR(255)
                );
            END IF;
        END
        $$;
    , parameters: None
[2025-02-27T13:16:20.537+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_details, 2200) already exists.
CONTEXT:  SQL statement "CREATE TABLE velib_station_details (
                    station_id BIGINT PRIMARY KEY, 
                    capacity INT,                   
                    lat DOUBLE PRECISION,          
                    lon DOUBLE PRECISION,           
                    name VARCHAR(255)
                )"
PL/pgSQL function inline_code_block line 7 at SQL statement

[2025-02-27T13:16:20.543+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=create_station_informations_table, execution_date=20250227T131618, start_date=20250227T131620, end_date=20250227T131620
[2025-02-27T13:16:20.551+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task create_station_informations_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_details, 2200) already exists.
CONTEXT:  SQL statement "CREATE TABLE velib_station_details (
                    station_id BIGINT PRIMARY KEY, 
                    capacity INT,                   
                    lat DOUBLE PRECISION,          
                    lon DOUBLE PRECISION,           
                    name VARCHAR(255)
                )"
PL/pgSQL function inline_code_block line 7 at SQL statement
; 210)
[2025-02-27T13:16:20.565+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-27T13:16:20.583+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
