[2025-02-28T17:28:57.516+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.index_parquet_to_elasticsearch manual__2025-02-28T17:28:44.306013+00:00 [queued]>
[2025-02-28T17:28:57.522+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.index_parquet_to_elasticsearch manual__2025-02-28T17:28:44.306013+00:00 [queued]>
[2025-02-28T17:28:57.522+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-28T17:28:57.529+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): index_parquet_to_elasticsearch> on 2025-02-28 17:28:44.306013+00:00
[2025-02-28T17:28:57.533+0000] {standard_task_runner.py:57} INFO - Started process 40683 to run task
[2025-02-28T17:28:57.535+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'index_parquet_to_elasticsearch', 'manual__2025-02-28T17:28:44.306013+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpst3sxexm']
[2025-02-28T17:28:57.536+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask index_parquet_to_elasticsearch
[2025-02-28T17:28:57.565+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.index_parquet_to_elasticsearch manual__2025-02-28T17:28:44.306013+00:00 [running]> on host 2e469bce1432
[2025-02-28T17:28:57.614+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='index_parquet_to_elasticsearch' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T17:28:44.306013+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T17:28:44.306013+00:00'
[2025-02-28T17:28:57.644+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag.py", line 57, in index_parquet_to_elasticsearch
    df = pd.read_parquet(parquet_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 236, in read
    mode="rb",
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/usage/velib_analytics/20250228/20250228T172857.parquet'
[2025-02-28T17:28:57.650+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=index_parquet_to_elasticsearch, execution_date=20250228T172844, start_date=20250228T172857, end_date=20250228T172857
[2025-02-28T17:28:57.656+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 47 for task index_parquet_to_elasticsearch ([Errno 2] No such file or directory: '/mnt/data/usage/velib_analytics/20250228/20250228T172857.parquet'; 40683)
[2025-02-28T17:28:57.675+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-28T17:28:57.687+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
