[2025-02-27T10:59:31.200+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.create_velib_station_status_table manual__2025-02-27T10:59:29.676432+00:00 [queued]>
[2025-02-27T10:59:31.205+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.create_velib_station_status_table manual__2025-02-27T10:59:29.676432+00:00 [queued]>
[2025-02-27T10:59:31.206+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-27T10:59:31.216+0000] {taskinstance.py:1350} INFO - Executing <Task(PostgresOperator): create_velib_station_status_table> on 2025-02-27 10:59:29.676432+00:00
[2025-02-27T10:59:31.220+0000] {standard_task_runner.py:57} INFO - Started process 181 to run task
[2025-02-27T10:59:31.249+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'create_velib_station_status_table', 'manual__2025-02-27T10:59:29.676432+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpit9hu6cq']
[2025-02-27T10:59:31.252+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask create_velib_station_status_table
[2025-02-27T10:59:31.358+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.create_velib_station_status_table manual__2025-02-27T10:59:29.676432+00:00 [running]> on host 3d206dcce365
[2025-02-27T10:59:31.463+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='create_velib_station_status_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-27T10:59:29.676432+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-27T10:59:29.676432+00:00'
[2025-02-27T10:59:31.463+0000] {sql.py:262} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS velib_stations(
                station_id BIGINT PRIMARY KEY,
                is_installed INT,
                is_renting INT,
                is_returning INT,
                last_reported TIMESTAMP,
                numBikesAvailable INT,
                numDocksAvailable INT,
                num_bikes_available INT,
                num_ebikes_available INT,
                num_mechanical_bikes_available INT,
                num_docks_available INT
            );
            
[2025-02-27T10:59:31.476+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-27T10:59:31.633+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-27T10:59:31.637+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS velib_stations(
                station_id BIGINT PRIMARY KEY,
                is_installed INT,
                is_renting INT,
                is_returning INT,
                last_reported TIMESTAMP,
                numBikesAvailable INT,
                numDocksAvailable INT,
                num_bikes_available INT,
                num_ebikes_available INT,
                num_mechanical_bikes_available INT,
                num_docks_available INT
            );
            , parameters: None
[2025-02-27T10:59:31.644+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 274, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_stations, 2200) already exists.

[2025-02-27T10:59:31.650+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=create_velib_station_status_table, execution_date=20250227T105929, start_date=20250227T105931, end_date=20250227T105931
[2025-02-27T10:59:31.658+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 2 for task create_velib_station_status_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_stations, 2200) already exists.
; 181)
[2025-02-27T10:59:31.694+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-27T10:59:31.727+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
