[2025-02-26T17:44:37.780+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: api_to_db_dag.create_velib_station_status_table manual__2025-02-26T17:44:36.594614+00:00 [queued]>
[2025-02-26T17:44:37.787+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: api_to_db_dag.create_velib_station_status_table manual__2025-02-26T17:44:36.594614+00:00 [queued]>
[2025-02-26T17:44:37.788+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-02-26T17:44:37.788+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-02-26T17:44:37.788+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-02-26T17:44:37.796+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_velib_station_status_table> on 2025-02-26 17:44:36.594614+00:00
[2025-02-26T17:44:37.800+0000] {standard_task_runner.py:55} INFO - Started process 182 to run task
[2025-02-26T17:44:37.802+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'create_velib_station_status_table', 'manual__2025-02-26T17:44:36.594614+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmplheew0qw']
[2025-02-26T17:44:37.804+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_velib_station_status_table
[2025-02-26T17:44:37.841+0000] {task_command.py:389} INFO - Running <TaskInstance: api_to_db_dag.create_velib_station_status_table manual__2025-02-26T17:44:36.594614+00:00 [running]> on host c783aa80544b
[2025-02-26T17:44:37.883+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_to_db_dag
AIRFLOW_CTX_TASK_ID=create_velib_station_status_table
AIRFLOW_CTX_EXECUTION_DATE=2025-02-26T17:44:36.594614+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-26T17:44:36.594614+00:00
[2025-02-26T17:44:37.883+0000] {sql.py:253} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS velib_station_table(
                station_id INT,
                is_installed BOOLEAN,
                is_renting BOOLEAN,
                is_returning BOOLEAN,
                last_reported TIMESTAMP,
                numBikesAvailable INT,
                numDocksAvailable INT,
                num_bikes_available INT,
                num_ebikes_available INT,
                num_mechanical_bikes_available INT,
                num_docks_available INT
            );
            
[2025-02-26T17:44:37.888+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-26T17:44:38.014+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-26T17:44:38.016+0000] {sql.py:364} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS velib_station_table(
                station_id INT,
                is_installed BOOLEAN,
                is_renting BOOLEAN,
                is_returning BOOLEAN,
                last_reported TIMESTAMP,
                numBikesAvailable INT,
                numDocksAvailable INT,
                num_bikes_available INT,
                num_ebikes_available INT,
                num_mechanical_bikes_available INT,
                num_docks_available INT
            );
            , parameters: None
[2025-02-26T17:44:38.018+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_table, 2200) already exists.

[2025-02-26T17:44:38.023+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=create_velib_station_status_table, execution_date=20250226T174436, start_date=20250226T174437, end_date=20250226T174438
[2025-02-26T17:44:38.029+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_velib_station_status_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_table, 2200) already exists.
; 182)
[2025-02-26T17:44:38.063+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-02-26T17:44:38.079+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
