[2025-03-02T19:00:03.731+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [queued]>
[2025-03-02T19:00:03.738+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [queued]>
[2025-03-02T19:00:03.738+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-02T19:00:03.750+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): save_raw_station_details_information> on 2025-03-02 18:45:00+00:00
[2025-03-02T19:00:03.755+0000] {standard_task_runner.py:57} INFO - Started process 15452 to run task
[2025-03-02T19:00:03.759+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'save_raw_station_details_information', 'scheduled__2025-03-02T18:45:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpux3qr85s']
[2025-03-02T19:00:03.761+0000] {standard_task_runner.py:85} INFO - Job 149: Subtask save_raw_station_details_information
[2025-03-02T19:00:03.806+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [running]> on host 3befbd719c1b
[2025-03-02T19:00:03.863+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='save_raw_station_details_information' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T18:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T18:45:00+00:00'
[2025-03-02T19:00:03.917+0000] {datalake_saver.py:45} INFO - Data saved successfully to /mnt/data/raw/velib_api/station_information/20250302/202503021900.json
[2025-03-02T19:00:03.917+0000] {python.py:183} INFO - Done. Returned value was: /mnt/data/raw/velib_api/station_information/20250302/202503021900.json
[2025-03-02T19:00:03.933+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=api_to_db_dag, task_id=save_raw_station_details_information, execution_date=20250302T184500, start_date=20250302T190003, end_date=20250302T190003
[2025-03-02T19:00:03.981+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-02T19:00:04.002+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-02T19:01:57.120+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [queued]>
[2025-03-02T19:01:57.141+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [queued]>
[2025-03-02T19:01:57.141+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-02T19:01:57.161+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): save_raw_station_details_information> on 2025-03-02 18:45:00+00:00
[2025-03-02T19:01:57.170+0000] {standard_task_runner.py:57} INFO - Started process 21331 to run task
[2025-03-02T19:01:57.172+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-02T19:01:57.179+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'save_raw_station_details_information', 'scheduled__2025-03-02T18:45:00+00:00', '--job-id', '157', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzmfjxej1']
[2025-03-02T19:01:57.181+0000] {standard_task_runner.py:85} INFO - Job 157: Subtask save_raw_station_details_information
[2025-03-02T19:01:57.246+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [running]> on host 3befbd719c1b
[2025-03-02T19:01:57.292+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-03-02T19:01:57.302+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-02T19:01:57.302+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 507, in send_command
    "Error while sending", e, proto.ERROR_ON_SEND)
py4j.protocol.Py4JNetworkError: Error while sending
[2025-03-02T19:01:57.309+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-02T19:01:57.351+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='save_raw_station_details_information' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T18:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T18:45:00+00:00'
[2025-03-02T19:01:57.470+0000] {datalake_saver.py:45} INFO - Data saved successfully to /mnt/data/raw/velib_api/station_information/20250302/202503021901.json
[2025-03-02T19:01:57.471+0000] {python.py:183} INFO - Done. Returned value was: /mnt/data/raw/velib_api/station_information/20250302/202503021901.json
[2025-03-02T19:01:57.490+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=api_to_db_dag, task_id=save_raw_station_details_information, execution_date=20250302T184500, start_date=20250302T190157, end_date=20250302T190157
[2025-03-02T19:01:57.529+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-02T19:01:57.567+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-02T19:07:05.236+0000] {taskinstance.py:1119} INFO - Dependencies not met for <TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0), upstream_task_ids={'get_station_information'}
[2025-03-02T19:07:05.248+0000] {local_task_job_runner.py:161} INFO - Task is not able to be run
[2025-03-02T19:07:26.104+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [queued]>
[2025-03-02T19:07:26.116+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [queued]>
[2025-03-02T19:07:26.117+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2025-03-02T19:07:26.140+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): save_raw_station_details_information> on 2025-03-02 18:45:00+00:00
[2025-03-02T19:07:26.190+0000] {standard_task_runner.py:57} INFO - Started process 44110 to run task
[2025-03-02T19:07:26.191+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-03-02T19:07:26.206+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'save_raw_station_details_information', 'scheduled__2025-03-02T18:45:00+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpqy_5z_0g']
[2025-03-02T19:07:26.211+0000] {standard_task_runner.py:85} INFO - Job 175: Subtask save_raw_station_details_information
[2025-03-02T19:07:26.324+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.save_raw_station_details_information scheduled__2025-03-02T18:45:00+00:00 [running]> on host 3befbd719c1b
[2025-03-02T19:07:26.500+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='save_raw_station_details_information' AIRFLOW_CTX_EXECUTION_DATE='2025-03-02T18:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-02T18:45:00+00:00'
[2025-03-02T19:07:26.614+0000] {datalake_saver.py:45} INFO - Data saved successfully to /mnt/data/raw/velib_api/station_information/20250302/202503021907.json
[2025-03-02T19:07:26.615+0000] {python.py:183} INFO - Done. Returned value was: /mnt/data/raw/velib_api/station_information/20250302/202503021907.json
[2025-03-02T19:07:26.682+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=api_to_db_dag, task_id=save_raw_station_details_information, execution_date=20250302T184500, start_date=20250302T190726, end_date=20250302T190726
[2025-03-02T19:07:26.714+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-03-02T19:07:26.775+0000] {taskinstance.py:2674} INFO - 1 downstream tasks scheduled from follow-on schedule check
