[2025-02-26T21:01:43.198+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-26T21:01:42.481352+00:00 [queued]>
[2025-02-26T21:01:43.209+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-26T21:01:42.481352+00:00 [queued]>
[2025-02-26T21:01:43.210+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-02-26T21:01:43.210+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2025-02-26T21:01:43.210+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-02-26T21:01:43.221+0000] {taskinstance.py:1304} INFO - Executing <Task(PostgresOperator): create_station_informations_table> on 2025-02-26 21:01:42.481352+00:00
[2025-02-26T21:01:43.227+0000] {standard_task_runner.py:55} INFO - Started process 200 to run task
[2025-02-26T21:01:43.231+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'create_station_informations_table', 'manual__2025-02-26T21:01:42.481352+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpeu91wc1_']
[2025-02-26T21:01:43.234+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask create_station_informations_table
[2025-02-26T21:01:43.300+0000] {task_command.py:389} INFO - Running <TaskInstance: api_to_db_dag.create_station_informations_table manual__2025-02-26T21:01:42.481352+00:00 [running]> on host 31a764ff7239
[2025-02-26T21:01:43.351+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=api_to_db_dag
AIRFLOW_CTX_TASK_ID=create_station_informations_table
AIRFLOW_CTX_EXECUTION_DATE=2025-02-26T21:01:42.481352+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-02-26T21:01:42.481352+00:00
[2025-02-26T21:01:43.352+0000] {sql.py:253} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS velib_station_details (
            station_id BIGINT PRIMARY KEY, 
            capacity INT,                   
            lat DOUBLE PRECISION,          
            lon DOUBLE PRECISION,           
            name VARCHAR(255)               
        );
        
[2025-02-26T21:01:43.359+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-26T21:01:43.530+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-02-26T21:01:43.534+0000] {sql.py:364} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS velib_station_details (
            station_id BIGINT PRIMARY KEY, 
            capacity INT,                   
            lat DOUBLE PRECISION,          
            lon DOUBLE PRECISION,           
            name VARCHAR(255)               
        );
        , parameters: None
[2025-02-26T21:01:43.548+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 261, in execute
    return_last=self.return_last,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 338, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 369, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_details, 2200) already exists.

[2025-02-26T21:01:43.556+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=create_station_informations_table, execution_date=20250226T210142, start_date=20250226T210143, end_date=20250226T210143
[2025-02-26T21:01:43.565+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task create_station_informations_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(velib_station_details, 2200) already exists.
; 200)
[2025-02-26T21:01:43.574+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2025-02-26T21:01:43.607+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
