[2025-02-28T17:39:37.325+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_to_db_dag.index_parquet_to_elasticsearch manual__2025-02-28T17:39:22.764908+00:00 [queued]>
[2025-02-28T17:39:37.331+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_to_db_dag.index_parquet_to_elasticsearch manual__2025-02-28T17:39:22.764908+00:00 [queued]>
[2025-02-28T17:39:37.331+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-28T17:39:37.342+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): index_parquet_to_elasticsearch> on 2025-02-28 17:39:22.764908+00:00
[2025-02-28T17:39:37.346+0000] {standard_task_runner.py:57} INFO - Started process 41825 to run task
[2025-02-28T17:39:37.349+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'api_to_db_dag', 'index_parquet_to_elasticsearch', 'manual__2025-02-28T17:39:22.764908+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpvvcrrope']
[2025-02-28T17:39:37.351+0000] {standard_task_runner.py:85} INFO - Job 63: Subtask index_parquet_to_elasticsearch
[2025-02-28T17:39:37.382+0000] {task_command.py:410} INFO - Running <TaskInstance: api_to_db_dag.index_parquet_to_elasticsearch manual__2025-02-28T17:39:22.764908+00:00 [running]> on host 2e469bce1432
[2025-02-28T17:39:37.442+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_to_db_dag' AIRFLOW_CTX_TASK_ID='index_parquet_to_elasticsearch' AIRFLOW_CTX_EXECUTION_DATE='2025-02-28T17:39:22.764908+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-28T17:39:22.764908+00:00'
[2025-02-28T17:39:37.444+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: index_parquet_to_elasticsearch() missing 1 required positional argument: 'directory_path'
[2025-02-28T17:39:37.450+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=api_to_db_dag, task_id=index_parquet_to_elasticsearch, execution_date=20250228T173922, start_date=20250228T173937, end_date=20250228T173937
[2025-02-28T17:39:37.460+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 63 for task index_parquet_to_elasticsearch (index_parquet_to_elasticsearch() missing 1 required positional argument: 'directory_path'; 41825)
[2025-02-28T17:39:37.488+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-28T17:39:37.500+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
